handleGHRelease: true
manifest: true
branches:
  - branch: main
    release-type: simple
  - branch: hotfix/1.0.1
    release-type: prerelease
    prerelease: true
    prerelease-label: hotfix
In this configuration:
